/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Control-Color.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Control Color
 #	author : miyako
 #	2023/09/19
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Control-Color.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Control Color
            
			case 1 :
				Get_control_color(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Get_control_color(PA_PluginParameters params) {

    CGFloat r, g, b, a;
    
    if (@available(macOS 10.14, *)) {
        NSColor *controlAccentColor = [NSColor controlAccentColor];

        controlAccentColor = [controlAccentColor colorUsingColorSpace:[NSColorSpace deviceRGBColorSpace]];
        
        [controlAccentColor getRed:&r green:&g blue:&b alpha:&a];
    }
    

    
    PA_ObjectRef returnValue = PA_CreateObject();
    ob_set_n(returnValue, L"red", r);
    ob_set_n(returnValue, L"green", g);
    ob_set_n(returnValue, L"blue", b);
    ob_set_n(returnValue, L"alpha", a);
    
    PA_ReturnObject(params, returnValue);
}

