/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Control-Color.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Control Color
 #	author : miyako
 #	2023/09/19
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Control-Color.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Control Color
            
			case 1 :
				Get_control_color(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Get_control_color(PA_PluginParameters params) {

}

