/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Control-Color.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Control Color
 #	author : miyako
 #	2023/09/19
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Control-Color.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Control Color
            
			case 1 :
				Get_control_color(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

#if VERSIONWIN
using namespace winrt;
using namespace Windows::UI::ViewManagement;
#endif

void Get_control_color(PA_PluginParameters params) {

#if VERSIONMAC

    CGFloat r, g, b, a;
    
    if (@available(macOS 10.14, *)) {
        NSColor *controlAccentColor = [NSColor controlAccentColor];

        controlAccentColor = [controlAccentColor colorUsingColorSpace:[NSColorSpace deviceRGBColorSpace]];
        
        [controlAccentColor getRed:&r green:&g blue:&b alpha:&a];
    }
    
#else

    double r, g, b, a;

    UISettings const ui_settings{};
    auto const accent_color{ ui_settings.GetColorValue(UIColorType::Accent) };
    r = accent_color.R;
    g = accent_color.G;
    b = accent_color.B;
    a = accent_color.A;
    r = r / 255;
    g = g / 255;
    b = b / 255;
    a = a / 255;
#endif

    
    PA_ObjectRef returnValue = PA_CreateObject();
    ob_set_n(returnValue, L"red", r);
    ob_set_n(returnValue, L"green", g);
    ob_set_n(returnValue, L"blue", b);
    ob_set_n(returnValue, L"alpha", a);
    
    PA_ReturnObject(params, returnValue);
}

